# Generated by Django 3.2.25 on 2024-03-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='balance_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
